apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      tka'
  creationTimestamp: 2018-09-13T19:07:33Z
  generateName: tka-55b5495645-
  labels:
    pod-template-hash: "1161051201"
    run: tka
  name: tka-55b5495645-7bgfr
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: tka-55b5495645
    uid: 758f6895-b782-11e8-b243-42010a80007c
  resourceVersion: "5226"
  selfLink: /api/v1/namespaces/default/pods/tka-55b5495645-7bgfr
  uid: 44ec3175-b788-11e8-b243-42010a80007c
spec:
  containers:
  - args:
    - port=8080
    - --generator=run/v1
    image: schamol/tka
    imagePullPolicy: Always
    name: tka
    resources:
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-d7jsl
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: gke-tka-1-default-pool-9bacc172-16ss
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-d7jsl
    secret:
      defaultMode: 420
      secretName: default-token-d7jsl
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-09-13T19:07:33Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-09-13T19:07:36Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-09-13T19:07:33Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a5efc3367a4dc43945b06c968f9e23344bd73473174b0f5143c7163ac0df3922
    image: schamol/tka:latest
    imageID: docker-pullable://schamol/tka@sha256:349077e86ba3e6f1cc97d3810e0913d8ffb0dd03cc0db4c74c1ac40c7db1a3d4
    lastState: {}
    name: tka
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-09-13T19:07:35Z
  hostIP: 10.128.0.4
  phase: Running
  podIP: 10.48.2.8
  qosClass: Burstable
  startTime: 2018-09-13T19:07:33Z
